import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import '../assets/scss/global.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import LayoutWrapper from '@/components/LayoutWrapper/LayoutWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <LayoutWrapper>{children}</LayoutWrapper>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
